# Creation of numpy Array

In [2]:
import numpy as np
arr= np.array([1,3,5,6,7])
print(arr)
print(type(arr))

[1 3 5 6 7]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
ar= np.array([(1,2,3),(4,5,6)])
print(ar)
print(type(ar))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [16]:
#Nested List 2d Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
print(np.__version__)

1.26.4


In [38]:
#2d Tuple
myTuple=((1, 2, 3, 4, 5),(1, 2, 3, 4, 5))
arr = np.array(myTuple)

print(arr)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [10]:
#3 D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[13, 14, 15], [20, 21, 22]]])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[13 14 15]
  [20 21 22]]]


In [21]:
#Check how many dimensions the arrays have
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
#d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
d= np.array([[[1,2,3],[4,5,6]],[[7,6,5],[3,5,8]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [46]:
#Empty function, Zeros function and ones function
arr2= np.empty((2,4),dtype='U') #random garbage values
print(arr2)

[['' '' '' '']
 ['' '' '' '']]


In [37]:
arr3= np.zeros((2,5),dtype=int)  
print(arr3)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [39]:
#The NumPy array object has a property called dtype that returns the data type of the array
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [40]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [56]:
#Create an array with data type 4 bytes integer:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# Array attribute

In [7]:
#Shape 
import numpy as np
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c.shape)

#c.shape=(3,2)  #Change resize of adarray
#print("\n",c)
print(c.reshape(3,2))
   

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


# Creation of array

In [12]:
#Empty function
import numpy as np
c = np.empty([3,3], dtype= int)
print(c.dtype)
print(c)

int32
[[      0       1       0]
 [    385     336       0]
 [    768   32762 4522067]]


In [23]:
#Eye function
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("Identity Matrix:")
print(identity_matrix)

# Create a 4x5 identity matrix with offset
identity_matrix_offset = np.eye(4,6, k=3,dtype=int)
print("\nIdentity Matrix with Offset:")
print(identity_matrix_offset)


Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Identity Matrix with Offset:
[[0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]]


In [24]:
#Identity matrix
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.identity(3)
print("Identity Matrix:")
print(identity_matrix)

# Create a 4x4 identity matrix
identity_matrix_4x4 = np.identity(4, dtype=int)
print("\nIdentity Matrix (4x4):")
print(identity_matrix_4x4)


Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Identity Matrix (4x4):
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [33]:
#The numpy.zeros() function creates an array filled with zeros.
import numpy as np

# Create a 2x3 array filled with zeros
zeros_array = np.zeros((2, 3),dtype=float)
print("Zeros Array:")
print(zeros_array)
print(zeros_array.dtype)

# Create a 3x2x2 array filled with zeros
zeros_3d_array = np.zeros((3, 2, 2))
print("\nZeros 3D Array:")
print(zeros_3d_array)


Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]
float64

Zeros 3D Array:
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [1]:
#Full funtion
import numpy as np

# Create a 2x3 array filled with 5
array_2d = np.full((2, 3), 98)
print("2D Array filled with 98:")
print(array_2d)

# Create a 3x2x2 array filled with pi
array_3d = np.full((3, 2, 2), np.pi)
print("\n3D Array filled with pi:")
print(array_3d)


2D Array filled with 98:
[[98 98 98]
 [98 98 98]]

3D Array filled with pi:
[[[3.14159265 3.14159265]
  [3.14159265 3.14159265]]

 [[3.14159265 3.14159265]
  [3.14159265 3.14159265]]

 [[3.14159265 3.14159265]
  [3.14159265 3.14159265]]]


In [7]:
import numpy as np

# Example 1: Convert a Python list to a NumPy array
python_list = [1, 2, 3, 4, 5]
numpy_array = np.asarray(python_list)
print("NumPy array from Python list:", numpy_array)

# Example 2: Convert a tuple to a NumPy array
python_tuple = (6, 7, 8, 9, 10)
numpy_array = np.asarray(python_tuple)
print("NumPy array from Python tuple:", numpy_array)

# Example 3: Convert a NumPy array to another NumPy array
original_array = np.array([11, 12, 13, 14, 15])
new_array = np.asarray(original_array)
print("Original NumPy array:", original_array)
print("New NumPy array from original array:", new_array)

# Example 4: Using dtype parameter to specify data type
original_list = [1.1, 2.2, 3.3, 4.4, 5.5]
numpy_array_float = np.asarray(original_list, dtype=np.float32)
print(numpy_array_float.dtype)
print("NumPy array with specified data type:", numpy_array_float)


NumPy array from Python list: [1 2 3 4 5]
NumPy array from Python tuple: [ 6  7  8  9 10]
Original NumPy array: [11 12 13 14 15]
New NumPy array from original array: [11 12 13 14 15]
float32
NumPy array with specified data type: [1.1 2.2 3.3 4.4 5.5]


In [8]:
#Testing Precision between float32 and float64
import numpy as np

# Define a decimal number with high precision
decimal_number = 1234567890.123456789

# Convert the decimal number to float32 and float64
float32_number = np.float32(decimal_number)
float64_number = np.float64(decimal_number)

# Print the converted numbers
print("Original Decimal Number:", decimal_number)
print("Converted to float32:", float32_number)
print("Converted to float64:", float64_number)


Original Decimal Number: 1234567890.1234567
Converted to float32: 1234568000.0
Converted to float64: 1234567890.1234567


In [13]:
import numpy as np

# Define a decimal number with high precision
decimal_number = 12366666.123456789

# Convert the decimal number to float32 and float64
float32_number = np.float32(decimal_number)
float64_number = np.float64(decimal_number)

# Print the converted numbers
print("Original Decimal Number:", decimal_number)
print("Converted to float32:", float32_number)
print("Converted to float64:", float64_number)

Original Decimal Number: 12366666.12345679
Converted to float32: 12366666.0
Converted to float64: 12366666.12345679


In [14]:
import numpy as np

# Example with int8
numpy_array_int8 = np.array([1, 2, 3], dtype=np.int8)
print("NumPy array with int8 data type:", numpy_array_int8)

# Example with int32
numpy_array_int32 = np.array([1, 2, 3], dtype=np.int32)
print("NumPy array with int32 data type:", numpy_array_int32)

# Example with int64
numpy_array_int64 = np.array([1, 2, 3], dtype=np.int64)
print("NumPy array with int64 data type:", numpy_array_int64)


NumPy array with int8 data type: [1 2 3]
NumPy array with int32 data type: [1 2 3]
NumPy array with int64 data type: [1 2 3]


In [20]:
numpy_array_int32 = np.array([1, 2, 3], dtype=int)
print(numpy_array_int32.dtype)
print("NumPy array with int32 data type:", numpy_array_int32)

int32
NumPy array with int32 data type: [1 2 3]


## Array from existing data

In [30]:
#asmatrix() is equivalent to matrix(data, copy=False)
#to convert arrays into matrices, especially when dealing with linear algebraic operations.

import numpy as np

# Example 1: Using asmatrix() to create a matrix from an array
array = np.array([[1, 2], [3, 4]])
matrix_from_array = np.asmatrix(array)
print("Matrix created from array using asmatrix():")
print(matrix_from_array)
print(type(matrix_from_array))
matrix_from_array[0,1]=76 # Changibg the value of elements
print(matrix_from_array)

# Example 2: Using matrix() to create a matrix from data
data = [[1, 2], [3, 4]]
matrix_from_data = np.matrix(data,copy=False)
print("\nMatrix created from data using matrix():")
print(matrix_from_data)
print(type(matrix_from_data))


Matrix created from array using asmatrix():
[[1 2]
 [3 4]]
<class 'numpy.matrix'>
[[ 1 76]
 [ 3  4]]

Matrix created from data using matrix():
[[1 2]
 [3 4]]
<class 'numpy.matrix'>


In [19]:
#Fromiter()
import numpy as np

# Define an iterable object (e.g., a list)
list=[1,2,3,4,5,6]
print(list[2:4])
my_list = range(5)

# Create a numpy array from the iterable using fromiter()
array_from_iter = np.fromiter(my_list, dtype=int,count=-1)

# Print the resulting numpy array
print("Numpy array created from the iterable object:")
print(array_from_iter)


[3, 4]
Numpy array created from the iterable object:
[0 1 2 3 4]


In [23]:
#Copy() and view() 
import numpy as np

# Original array
original_array = np.array([1, 2, 3, 4, 5])

# Create a copy of the original array
copied_array = np.copy(original_array)

# Modify the copied array
copied_array[0] = 100

# Print both arrays
print("Original Array:", original_array)
print("Copied Array:", copied_array)


Original Array: [1 2 3 4 5]
Copied Array: [100   2   3   4   5]


In [21]:
# Original array
original_array = np.array([1, 2, 3, 4, 5])

# Create a view of the original array
view_array = original_array.view()

# Modify the view array
view_array[0] = 100

# Print both arrays
print("Original Array:", original_array)
print("View Array:", view_array)

Original Array: [100   2   3   4   5]
View Array: [100   2   3   4   5]


In [27]:
#arange()
import numpy as np

# Create an array of integers from 0 to 9
array1 = np.arange(10)

# Print the resulting array
print("Array from 0 to 9:")
print(array1)

# Create an array of even numbers from 2 to 10 (exclusive)
array2 = np.arange(2, 11, 2)

# Print the resulting array
print("\nArray of even numbers from 2 to 10:")
print(array2)

# Create an array of floating-point numbers from 0 to 1 with a step of 0.1
array3 = np.arange(0, 1, 0.1)

# Print the resulting array
print("\nArray from 0 to 1 with a step of 0.1:")
print(array3)


Array from 0 to 9:
[0 1 2 3 4 5 6 7 8 9]

Array of even numbers from 2 to 10:
[ 2  4  6  8 10]

Array from 0 to 1 with a step of 0.1:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


## Indexing and Slicing

In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4])
#Accessing  third and fourth elements from the following array and add them
print(arr[2] + arr[3])

7


In [35]:
#2 D arrays
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr[0,1]= 32
print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])

2nd element on 1st row:  32
5th element on 2nd row:  10


In [37]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -3])

Last element from 2nd dim:  8


In [40]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [1]:
#all elements of th e array
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::])

[1 2 3 4 5 6 7]


In [42]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

5


In [2]:
#From the second element, slice elements from index 1 to index 4 (not included):

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])


[7 8 9]


In [5]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[:, 1:4])

[[2 3 4]
 [7 8 9]]


In [53]:
#From both elements, return index 2:

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])
print(arr[0:2, 2:5])

[3 8]
[[ 3  4  5]
 [ 8  9 10]]


In [54]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [57]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,14])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 14]]


## iterating of arrays 

In [59]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [60]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [61]:
#Iterate on each scalar element of the 2-D array:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [62]:
#Iterate through the following 3-D array:

import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)


1
2
3
4
5
6
7
8


In [63]:
#Join two arrays

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [67]:
#numpy.concatenate((a1, a2, ...), axis=0, out=None)
import numpy as np

# Creating two arrays to concatenate
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenating along axis 0 (default)
result = np.concatenate((arr1, arr2),axis=0) 
print(result)  # Output: [1 2 3 4 5 6]


[1 2 3 4 5 6]


In [68]:
import numpy as np

# Creating two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenating along axis 0 (rows)
result_axis_0 = np.concatenate((arr1, arr2), axis=0)
print("Concatenation along axis 0:")
print(result_axis_0)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

# Concatenating along axis 1 (columns)
result_axis_1 = np.concatenate((arr1, arr2), axis=1)
print("\nConcatenation along axis 1:")
print(result_axis_1)
# Output:
# [[1 2 5 6]
#  [3 4 7 8]]


Concatenation along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenation along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [69]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [75]:
#NumPy provides a helper function: hstack() to stack along column.

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))
print(np.shape(arr))
print(arr)

(6,)
[1 2 3 4 5 6]


In [76]:
#NumPy provides a helper function: vstack()  to stack along rows.


import numpy as np

arr1 = np.array([1, 2, 3,4])

arr2 = np.array([4, 5, 6,5])
arr3 = np.array([7,8,9,9])

arr = np.vstack((arr1, arr2,arr3))
print(np.shape(arr))

print(arr)

(3, 4)
[[1 2 3 4]
 [4 5 6 5]
 [7 8 9 9]]


In [77]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [78]:
#split an array into multiple sub-arrays along a specified axis
import numpy as np

arr = np.arange(10)  # Creating an array [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
sub_arrays = np.array_split(arr, 3)  # Splitting the array into 3 sub-arrays
print(sub_arrays)


[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [79]:
#Split the array in 4 parts:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [80]:
#If you split an array into 3 arrays, you can access them from the result just like any array element
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [84]:
#Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
print(arr)
print()
newarr = np.array_split(arr, 3)

print(newarr)
print()
print(newarr[2])
arr3=newarr[1,0:2]
print(arr3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]

[[ 9 10]
 [11 12]]


TypeError: list indices must be integers or slices, not tuple

In [86]:
#Split the 2-D array into three 2-D arrays along rows.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [89]:
#An alternate solution is using hsplit() opposite of hstack()

#Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [90]:
#Find the indexes where the value is 4:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [91]:
#Find the indexes where the values are odd:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [92]:
#Sort the array:

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [93]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [94]:
#Sort a 2-D array:

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [95]:
import numpy as np

# Define an example array
arr = np.array([[3, 2, 1], [6, 5, 4]])

# Original array
print("Original array:")
print(arr)

# Sorting along the last axis (axis=-1 by default)
sorted_arr_axis = np.sort(arr)
print("\nSorted along the last axis (default):")
print(sorted_arr_axis)

# Sorting along the first axis
sorted_arr_axis_0 = np.sort(arr, axis=0)
print("\nSorted along the first axis:")
print(sorted_arr_axis_0)

# Using mergesort algorithm
sorted_arr_mergesort = np.sort(arr, kind='mergesort')
print("\nSorted using mergesort algorithm:")
print(sorted_arr_mergesort)

# Using heapsort algorithm
sorted_arr_heapsort = np.sort(arr, kind='heapsort')
print("\nSorted using heapsort algorithm:")
print(sorted_arr_heapsort)

# Sorting with a specified order
dtype = [('name', 'S10'), ('age', int)]
values = [('John', 25), ('Jane', 30), ('Dave', 20)]
arr_structured = np.array(values, dtype=dtype)
sorted_arr_order = np.sort(arr_structured, order='age')
print("\nSorted structured array by age:")
print(sorted_arr_order)


Original array:
[[3 2 1]
 [6 5 4]]

Sorted along the last axis (default):
[[1 2 3]
 [4 5 6]]

Sorted along the first axis:
[[3 2 1]
 [6 5 4]]

Sorted using mergesort algorithm:
[[1 2 3]
 [4 5 6]]

Sorted using heapsort algorithm:
[[1 2 3]
 [4 5 6]]

Sorted structured array by age:
[(b'Dave', 20) (b'John', 25) (b'Jane', 30)]


In [1]:
#Sum()
import numpy as np

# Define an array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Sum all elements of the array
total_sum = np.sum(arr)
print("Total sum of all elements:", total_sum)

# Sum along axis 0 (columns)
sum_axis_0 = np.sum(arr, axis=0)
print("Sum along axis 0 (columns):", sum_axis_0)

# Sum along axis 1 (rows)
sum_axis_1 = np.sum(arr, axis=1)
print("Sum along axis 1 (rows):", sum_axis_1)


Total sum of all elements: 21
Sum along axis 0 (columns): [5 7 9]
Sum along axis 1 (rows): [ 6 15]


In [2]:
#Create an array from the elements on index 0 and 2:

import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [4]:
#Create a filter array that will return only values higher than 42:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
boolList = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    boolList.append(True)
  else:
    boolList.append(False)

newarr = arr[boolList]

print(boolList)
print(newarr)

[False, False, True, True]
[43 44]


In [1]:
#example of how you can slice a two-dimensional pandas DataFrame using Python
import pandas as pd

# Creating a sample DataFrame
data = {
    'A': [1, 2, 3, 4, 5],
    'B': [6, 7, 8, 9, 10],
    'C': [11, 12, 13, 14, 15]
}

df = pd.DataFrame(data)
print(df)
print()

# Slicing rows and columns
# Syntax: DataFrame.loc[row_selection, column_selection]

# Selecting rows 1 to 3 and columns 'B' and 'C'
sliced_df = df.loc[1:3, ['B', 'C']]

print(sliced_df)


   A   B   C
0  1   6  11
1  2   7  12
2  3   8  13
3  4   9  14
4  5  10  15

   B   C
1  7  12
2  8  13
3  9  14


## Reshape()

In [12]:
#Convert the following 1-D array with 12 elements into a 2-D array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.shape)
newarr = arr.reshape(12,1)

print(newarr)
newarr.shape

(12,)
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


(12, 1)

In [4]:
#Convert the array into a 1D array:using reshape(-1)

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

#newarr = np.reshape(arr,(4, 3))
newarr = arr.reshape()
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [9]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2),axis=0)

print(arr)

[1 2 3 4 5 6]


In [18]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
print(arr1)
print()

arr2 = np.array([[5, 6], [7, 8]])
print(arr2,'\n')
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

#'''When axis=1, the arrays are joined along rows, resulting in an array with the same number of rows and the sum of columns from both arrays.
#When axis=0, the arrays are joined along columns, resulting in an array with the same number of columns and the sum of rows from both arrays.'''

[[1 2]
 [3 4]]

[[5 6]
 [7 8]] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [20]:
#Sort a 2-D array:

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [24]:
def my_function(child3, child2, child1):
  print("The youngest child is " + child3)

my_function(child1 = "Emil",child3 = "Linus" ,child2 = "Tobias")

The youngest child is Linus
